{{- if .Values.platform.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "n8n-platform.fullname" . }}
  labels:
    {{- include "n8n-platform.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.platform.ingress.entrypoints }}
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: {{ .Values.platform.ingress.className }}
  {{- if .Values.platform.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.platform.ingress.host }}
      secretName: {{ .Values.platform.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.platform.ingress.host }}
      http:
        paths:
          - path: {{ .Values.platform.ingress.path }}
            pathType: {{ .Values.platform.ingress.pathType }}
            backend:
              service:
                name: {{ include "n8n-platform.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
