apiVersion: v1
kind: Service
metadata:
  name: {{ include "hotel.fullname" . }}-frontend-preview
  labels:
    {{- include "hotel.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-preview
spec:
  type: ClusterIP
  selector:
    {{- include "hotel.frontendSelectorLabels" . | nindent 4 }}
    {{- if not (include "hotel.rolloutEnabled" .) }}
    hotel/slot: {{ include "hotel.previewSlot" . }}
    {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.frontendPort }}
      targetPort: http
