apiVersion: v1
kind: Service
metadata:
  name: {{ include "hotel.fullname" . }}-backend
  labels:
    {{- include "hotel.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "hotel.backendSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.backendPort }}
      targetPort: http
