apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-web.fullname" . }}
  labels:
    {{- include "generic-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "generic-web.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ include "arkhadia-common.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount | default false }}
      securityContext:
        {{- include "arkhadia-common.podSecurityContext" . | nindent 8 }}
      {{- include "arkhadia-common.topologySpread" (dict "ctx" . "selectorLabels" (include "generic-web.selectorLabels" .)) | nindent 6 }}
      {{- include "arkhadia-common.podAntiAffinity" (dict "ctx" . "selectorLabels" (include "generic-web.selectorLabels" .)) | nindent 6 }}
      containers:
        - name: {{ include "generic-web.name" . }}
          image: "{{ include "arkhadia-common.image" .Values.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- include "arkhadia-common.containerSecurityContext" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          {{- if .Values.platform.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.platform.envFromSecret }}
          {{- end }}
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
